import { useStore } from '../store/useStore'
import { summaryStats } from '../lib/stats'
import { correlationMatrix } from '../lib/stats'
import { Download, FileCode, FileText, Printer, Table2 } from 'lucide-react'
import * as XLSX from 'xlsx'
import { Link } from 'react-router-dom'
import { Upload } from 'lucide-react'
import { escapeHtml } from '../lib/validation'

export function ReportsPage() {
  const { activeDataset } = useStore()

  if (!activeDataset) {
    return (
      <div className="flex flex-col items-center justify-center h-full gap-4 text-slate-400">
        <Upload size={48} />
        <p className="text-lg font-medium">No dataset loaded</p>
        <Link to="/data/upload" className="text-sm bg-indigo-600 text-white px-4 py-2 rounded-md hover:bg-indigo-700">Upload Data</Link>
      </div>
    )
  }

  const numCols = activeDataset.schema.filter((c) => c.type === 'numeric').map((c) => c.name)

  const exportFullDataCSV = () => {
    const ws = XLSX.utils.json_to_sheet(activeDataset.data)
    const wb = XLSX.utils.book_new()
    XLSX.utils.book_append_sheet(wb, ws, 'Data')
    XLSX.writeFile(wb, `${activeDataset.name}_export.csv`, { bookType: 'csv' })
  }

  const exportFullDataExcel = () => {
    const dataWs = XLSX.utils.json_to_sheet(activeDataset.data)
    const wb = XLSX.utils.book_new()
    XLSX.utils.book_append_sheet(wb, dataWs, 'Data')

    // Add summary sheet
    if (numCols.length > 0) {
      const summaryRows: Record<string, unknown>[] = numCols.map((col) => {
        const s = summaryStats(activeDataset.data, col)
        const row: Record<string, unknown> = { Column: col }
        s.forEach((stat) => { row[stat.label] = stat.value })
        return row
      })
      const summaryWs = XLSX.utils.json_to_sheet(summaryRows)
      XLSX.utils.book_append_sheet(wb, summaryWs, 'Summary')
    }

    XLSX.writeFile(wb, `${activeDataset.name}_report.xlsx`)
  }

  const exportHTMLReport = () => {
    const stats = numCols.map((col) => ({ col, stats: summaryStats(activeDataset.data, col) }))
    const corr = numCols.length >= 2 ? correlationMatrix(activeDataset.data, numCols) : null

    const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Anveshak Report — ${activeDataset.name}</title>
<style>
  body { font-family: system-ui, sans-serif; margin: 40px; color: #1e293b; }
  h1 { color: #4f46e5; } h2 { color: #334155; border-bottom: 2px solid #e2e8f0; padding-bottom: 6px; }
  table { border-collapse: collapse; width: 100%; margin: 16px 0; }
  th, td { border: 1px solid #e2e8f0; padding: 8px 12px; text-align: left; font-size: 13px; }
  th { background: #f8fafc; font-weight: 600; }
  .meta { background: #f8fafc; padding: 12px 16px; border-radius: 8px; margin: 16px 0; font-size: 13px; }
  .footer { margin-top: 40px; color: #94a3b8; font-size: 12px; }
</style>
</head>
<body>
<h1>Anveshak Analysis Report</h1>
<div class="meta">
  <b>Dataset:</b> ${escapeHtml(activeDataset.name)} &nbsp;|&nbsp;
  <b>Rows:</b> ${activeDataset.rows.toLocaleString()} &nbsp;|&nbsp;
  <b>Columns:</b> ${activeDataset.cols} &nbsp;|&nbsp;
  <b>Generated:</b> ${new Date().toLocaleString()}
  <br><small>Data processed locally. No data was uploaded to any server.</small>
</div>

<h2>Column Schema</h2>
<table>
  <tr><th>Column</th><th>Type</th><th>Unique</th><th>Missing</th><th>Missing %</th></tr>
  ${activeDataset.schema.map((c) => `<tr><td>${escapeHtml(c.name)}</td><td>${escapeHtml(c.type)}</td><td>${c.unique}</td><td>${c.missing}</td><td>${c.missingPct.toFixed(1)}%</td></tr>`).join('')}
</table>

${stats.map(({ col, stats: s }) => `
<h2>Summary Statistics: ${escapeHtml(col)}</h2>
<table>
  <tr>${s.map((r) => `<th>${escapeHtml(r.label)}</th>`).join('')}</tr>
  <tr>${s.map((r) => `<td>${escapeHtml(r.value)}</td>`).join('')}</tr>
</table>
`).join('')}

${corr ? `
<h2>Correlation Matrix</h2>
<table>
  <tr><th></th>${corr.cols.map((c) => `<th>${escapeHtml(c)}</th>`).join('')}</tr>
  ${corr.matrix.map((row, i) => `<tr><th>${escapeHtml(corr.cols[i])}</th>${row.map((v) => `<td style="color:${Math.abs(v) > 0.7 ? '#dc2626' : '#334155'}">${v.toFixed(3)}</td>`).join('')}</tr>`).join('')}
</table>
` : ''}

<div class="footer">Generated by Anveshak — Browser-Only Statistics Platform · Data never left your browser.</div>
</body>
</html>`

    const blob = new Blob([html], { type: 'text/html' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${activeDataset.name}_report.html`
    a.click()
    URL.revokeObjectURL(url)
  }

  const reportMarkdown = () => {
    const schema = activeDataset.schema.map((c) => `| ${c.name} | ${c.type} | ${c.unique} | ${c.missing} | ${c.missingPct.toFixed(1)}% |`).join('\n')
    const stats = numCols.map((col) => {
      const row = summaryStats(activeDataset.data, col).map((s) => `- ${s.label}: ${s.value}`).join('\n')
      return `## ${col}\n${row}`
    }).join('\n\n')
    return `# Anveshak Analysis Report\n\nDataset: ${activeDataset.name}\nRows: ${activeDataset.rows}\nColumns: ${activeDataset.cols}\n\n## Schema\n| Column | Type | Unique | Missing | Missing % |\n|---|---:|---:|---:|---:|\n${schema}\n\n${stats}\n`
  }

  const downloadText = (name: string, content: string, type: string) => {
    const blob = new Blob([content], { type })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = name
    a.click()
    URL.revokeObjectURL(url)
  }

  const exportMarkdown = () => downloadText(`${activeDataset.name}_report.md`, reportMarkdown(), 'text/markdown')
  const exportScript = () => downloadText(`${activeDataset.name}_analysis.js`, `// Reproducible Anveshak analysis recipe\nconst dataset = "${activeDataset.name}"\nconst numericColumns = ${JSON.stringify(numCols, null, 2)}\n// 1. Load dataset\n// 2. Validate schema and missingness\n// 3. Run summary statistics for numericColumns\n// 4. Run correlation matrix when numericColumns.length >= 2\n// 5. Export report artifacts\n`, 'text/javascript')
  const exportWordCompatible = () => downloadText(`${activeDataset.name}_report.doc`, `<html><body><pre>${reportMarkdown().replace(/[<>&]/g, (c) => ({ '<': '&lt;', '>': '&gt;', '&': '&amp;' }[c] ?? c))}</pre></body></html>`, 'application/msword')
  const printPdf = () => window.print()

  return (
    <div className="p-6 max-w-3xl mx-auto">
      <h1 className="text-2xl font-bold text-slate-800 dark:text-white mb-6">Export & Reports</h1>

      <p className="text-sm text-slate-500 dark:text-slate-400 mb-8">
        All exports are generated locally in your browser. No data is sent to any server.
      </p>

      <div className="space-y-4">
        {[
          {
            icon: Table2,
            title: 'Export Data as CSV',
            desc: 'Download the full dataset as a CSV file',
            action: exportFullDataCSV,
            color: 'text-green-600',
            bg: 'bg-green-50 dark:bg-green-900/20',
          },
          {
            icon: Table2,
            title: 'Export Data as Excel (.xlsx)',
            desc: 'Download data + summary statistics in a multi-sheet Excel workbook',
            action: exportFullDataExcel,
            color: 'text-emerald-600',
            bg: 'bg-emerald-50 dark:bg-emerald-900/20',
          },
          {
            icon: FileText,
            title: 'Generate HTML Report',
            desc: 'Self-contained HTML report with schema, summary stats, and correlation matrix',
            action: exportHTMLReport,
            color: 'text-indigo-600',
            bg: 'bg-indigo-50 dark:bg-indigo-900/20',
          },
          {
            icon: FileText,
            title: 'Export Markdown Report',
            desc: 'Download a clean Markdown report for notebooks and docs',
            action: exportMarkdown,
            color: 'text-sky-600',
            bg: 'bg-sky-50 dark:bg-sky-900/20',
          },
          {
            icon: Printer,
            title: 'Print / Save as PDF',
            desc: 'Open the browser print dialog for PDF output',
            action: printPdf,
            color: 'text-purple-600',
            bg: 'bg-purple-50 dark:bg-purple-900/20',
          },
          {
            icon: FileCode,
            title: 'Export Reproducible Script',
            desc: 'Download a starter script documenting the analysis steps',
            action: exportScript,
            color: 'text-orange-600',
            bg: 'bg-orange-50 dark:bg-orange-900/20',
          },
          {
            icon: FileText,
            title: 'Export Word-Compatible .doc Report',
            desc: 'Download an HTML-backed .doc file that opens in Word',
            action: exportWordCompatible,
            color: 'text-blue-600',
            bg: 'bg-blue-50 dark:bg-blue-900/20',
          },
        ].map(({ icon: Icon, title, desc, action, color, bg }) => (
          <div key={title} className="bg-white dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700 p-5 flex items-center gap-4">
            <div className={`w-10 h-10 rounded-xl ${bg} flex items-center justify-center shrink-0`}>
              <Icon size={20} className={color} />
            </div>
            <div className="flex-1 min-w-0">
              <p className="font-semibold text-slate-700 dark:text-slate-200 text-sm">{title}</p>
              <p className="text-xs text-slate-400 mt-0.5">{desc}</p>
            </div>
            <button
              onClick={action}
              className="flex items-center gap-1.5 text-sm bg-slate-900 dark:bg-white dark:text-slate-900 hover:opacity-90 text-white px-4 py-2 rounded-lg transition-opacity shrink-0"
            >
              <Download size={14} /> Export
            </button>
          </div>
        ))}
      </div>
    </div>
  )
}
