import type { AnalysisDef, JaspModuleId } from './types'

const descriptives: AnalysisDef[] = [
  {
    id: 'descriptives.statistics',
    module: 'descriptives',
    moduleLabel: 'Descriptives',
    title: 'Descriptive Statistics',
    description: 'Valid/missing counts, mean, SE, CI, SD, variance, quantiles, skewness, kurtosis, mode, CV, and Shapiro–Wilk.',
    phase: 1,
    implemented: true,
    frequentist: true,
    bayesian: false,
    fields: [
      { key: 'variables', kind: 'variables', label: 'Variables', role: 'numeric', multiple: true, required: true },
      { key: 'splitBy', kind: 'select', label: 'Split by', role: 'categorical', required: false },
      { key: 'categorical', kind: 'variables', label: 'Frequency tables', role: 'categorical', multiple: true, required: false },
      { key: 'ciLevel', kind: 'number', label: 'Mean CI level', min: 0.8, max: 0.99, step: 0.01, required: false },
    ],
  },
  {
    id: 'descriptives.raincloud',
    module: 'descriptives',
    moduleLabel: 'Descriptives',
    title: 'Raincloud Plots',
    description: 'Half-violin density, Tukey box, mean line, and raw points by group.',
    phase: 1,
    implemented: true,
    frequentist: true,
    bayesian: false,
    fields: [
      { key: 'dependent', kind: 'select', label: 'Dependent', role: 'numeric', required: true },
      { key: 'group', kind: 'select', label: 'Group', role: 'categorical', required: false },
    ],
  },
  {
    id: 'descriptives.timeSeries',
    module: 'descriptives',
    moduleLabel: 'Descriptives',
    title: 'Time Series Descriptives',
    description: 'Series summary, linear trend, ACF, PACF, and optional seasonal means.',
    phase: 1,
    implemented: true,
    frequentist: true,
    bayesian: false,
    fields: [
      { key: 'variable', kind: 'select', label: 'Series', role: 'numeric', required: true },
      { key: 'period', kind: 'number', label: 'Seasonal period (optional)', min: 2, max: 366, step: 1, required: false },
    ],
  },
  {
    id: 'descriptives.flexplot',
    module: 'descriptives',
    moduleLabel: 'Descriptives',
    title: 'Flexplot',
    description: 'Univariate or bivariate Flexplot grammar: outcome, predictor, and optional split.',
    phase: 1,
    implemented: true,
    frequentist: true,
    bayesian: false,
    fields: [
      { key: 'outcome', kind: 'select', label: 'Outcome', role: 'numeric', required: true },
      { key: 'predictor', kind: 'select', label: 'Predictor', role: 'any', required: false },
      { key: 'split', kind: 'select', label: 'Split (color)', role: 'categorical', required: false },
      { key: 'overlay', kind: 'choice', label: 'Overlay', required: true, options: [
        { value: 'linear', label: 'Linear (OLS)' },
        { value: 'glm', label: 'GLM (binomial / Poisson / Gaussian)' },
        { value: 'mixed', label: 'Mixed (random intercept by split)' },
      ] },
      { key: 'glmFamily', kind: 'choice', label: 'GLM family', required: false, options: [
        { value: 'gaussian', label: 'Gaussian' },
        { value: 'binomial', label: 'Binomial' },
        { value: 'poisson', label: 'Poisson' },
      ] },
    ],
  },
]

const visualModeling: AnalysisDef[] = [{
  ...descriptives[3],
  id: 'visualModeling.flexplot',
  module: 'visualModeling',
  moduleLabel: 'Visual Modeling',
  title: 'Flexplot',
  description: 'Same Flexplot engine as Descriptives: linear, GLM, or mixed overlays.',
}]

const alt = [
  { value: 'two-sided', label: 'Two-sided' },
  { value: 'greater', label: 'Greater' },
  { value: 'less', label: 'Less' },
]

const phase2: AnalysisDef[] = [
  {
    id: 't.independent',
    module: 'tTests',
    moduleLabel: 'T-Tests',
    title: 'Independent Samples T-Test',
    description: 'Student or Welch t, Levene, Cohen’s d, optional Mann–Whitney. Bayesian t arrives in Phase 4.',
    phase: 2,
    implemented: true,
    frequentist: true,
    bayesian: false,
    fields: [
      { key: 'dependent', kind: 'select', label: 'Dependent', role: 'numeric', required: true },
      { key: 'group', kind: 'select', label: 'Grouping variable', role: 'categorical', required: true },
      { key: 'alternative', kind: 'choice', label: 'Alternative', required: true, options: alt },
      { key: 'equalVariance', kind: 'toggle', label: 'Equal variances (Student t)', default: false },
      { key: 'mannWhitney', kind: 'toggle', label: 'Mann–Whitney U', default: true },
    ],
  },
  {
    id: 't.paired',
    module: 'tTests',
    moduleLabel: 'T-Tests',
    title: 'Paired Samples T-Test',
    description: 'Paired t and optional Wilcoxon signed-rank. Bayesian paired t arrives in Phase 4.',
    phase: 2,
    implemented: true,
    frequentist: true,
    bayesian: false,
    fields: [
      { key: 'measure1', kind: 'select', label: 'Measure 1', role: 'numeric', required: true },
      { key: 'measure2', kind: 'select', label: 'Measure 2', role: 'numeric', required: true },
      { key: 'alternative', kind: 'choice', label: 'Alternative', required: true, options: alt },
      { key: 'wilcoxon', kind: 'toggle', label: 'Wilcoxon signed-rank', default: true },
    ],
  },
  {
    id: 't.oneSample',
    module: 'tTests',
    moduleLabel: 'T-Tests',
    title: 'One Sample T-Test',
    description: 'One-sample t vs a test value, optional Wilcoxon. Bayesian one-sample t arrives in Phase 4.',
    phase: 2,
    implemented: true,
    frequentist: true,
    bayesian: false,
    fields: [
      { key: 'variable', kind: 'select', label: 'Variable', role: 'numeric', required: true },
      { key: 'mu0', kind: 'number', label: 'Test value', required: true, default: 0, step: 0.1 },
      { key: 'alternative', kind: 'choice', label: 'Alternative', required: true, options: alt },
      { key: 'wilcoxon', kind: 'toggle', label: 'Wilcoxon signed-rank', default: true },
    ],
  },
  {
    id: 'anova.between',
    module: 'anova',
    moduleLabel: 'ANOVA',
    title: 'ANOVA',
    description: 'One- and two-way Type I/II/III ANOVA with Tukey, Bonferroni, Holm, Scheffé, and Games–Howell. Bayesian ANOVA arrives in Phase 4.',
    phase: 2,
    implemented: true,
    frequentist: true,
    bayesian: false,
    fields: [
      { key: 'dependent', kind: 'select', label: 'Dependent', role: 'numeric', required: true },
      { key: 'factors', kind: 'variables', label: 'Factors (1–2)', role: 'categorical', multiple: true, required: true },
      { key: 'ssType', kind: 'choice', label: 'Sum of squares', required: true, options: [{ value: 'III', label: 'Type III' }, { value: 'II', label: 'Type II' }, { value: 'I', label: 'Type I' }] },
      { key: 'postHoc', kind: 'checkboxGroup', label: 'Post-hoc', items: [
        { key: 'tukey', label: 'Tukey' },
        { key: 'bonferroni', label: 'Bonferroni' },
        { key: 'holm', label: 'Holm' },
        { key: 'scheffe', label: 'Scheffé' },
        { key: 'gamesHowell', label: 'Games–Howell' },
      ] },
    ],
  },
  {
    id: 'anova.repeated',
    module: 'anova',
    moduleLabel: 'ANOVA',
    title: 'Repeated Measures ANOVA',
    description: 'Wide-format RM ANOVA with Mauchly, Greenhouse–Geisser, and Huynh–Feldt. Bayesian RM ANOVA arrives in Phase 4.',
    phase: 2,
    implemented: true,
    frequentist: true,
    bayesian: false,
    fields: [
      { key: 'measures', kind: 'variables', label: 'Repeated measures', role: 'numeric', multiple: true, required: true },
    ],
  },
  {
    id: 'anova.ancova',
    module: 'anova',
    moduleLabel: 'ANOVA',
    title: 'ANCOVA',
    description: 'Type II ANCOVA with a homogeneity-of-slopes check. Bayesian ANCOVA arrives in Phase 4.',
    phase: 2,
    implemented: true,
    frequentist: true,
    bayesian: false,
    fields: [
      { key: 'dependent', kind: 'select', label: 'Dependent', role: 'numeric', required: true },
      { key: 'group', kind: 'select', label: 'Grouping factor', role: 'categorical', required: true },
      { key: 'covariate', kind: 'select', label: 'Covariate', role: 'numeric', required: true },
    ],
  },
  {
    id: 'anova.manova',
    module: 'anova',
    moduleLabel: 'ANOVA',
    title: 'MANOVA',
    description: 'Pillai, Wilks, Hotelling–Lawley, and Roy tests from eigenvalues of E⁻¹H.',
    phase: 2,
    implemented: true,
    frequentist: true,
    bayesian: false,
    fields: [
      { key: 'dependents', kind: 'variables', label: 'Outcomes', role: 'numeric', multiple: true, required: true },
      { key: 'group', kind: 'select', label: 'Grouping factor', role: 'categorical', required: true },
    ],
  },
]

const phase3: AnalysisDef[] = [
  {
    id: 'regression.correlation',
    module: 'regression',
    moduleLabel: 'Regression',
    title: 'Correlation',
    description: 'Pearson, Spearman, Kendall, and partial correlations. Bayesian correlation arrives in Phase 4.',
    phase: 3,
    implemented: true,
    frequentist: true,
    bayesian: false,
    fields: [
      { key: 'variables', kind: 'variables', label: 'Variables', role: 'numeric', multiple: true, required: true },
      { key: 'method', kind: 'choice', label: 'Method', required: true, options: [{ value: 'pearson', label: 'Pearson' }, { value: 'spearman', label: 'Spearman' }, { value: 'kendall', label: 'Kendall' }] },
      { key: 'controls', kind: 'variables', label: 'Covariates (partial)', role: 'numeric', multiple: true, required: false },
      { key: 'ciLevel', kind: 'number', label: 'CI level', min: 0.8, max: 0.99, step: 0.01, required: false },
    ],
  },
  {
    id: 'regression.linear',
    module: 'regression',
    moduleLabel: 'Regression',
    title: 'Linear Regression',
    description: 'OLS with factors, optional interactions, VIF, DW, Breusch–Pagan, RESET, and Cook diagnostics. Bayesian linear arrives in Phase 4.',
    phase: 3,
    implemented: true,
    frequentist: true,
    bayesian: false,
    fields: [
      { key: 'dependent', kind: 'select', label: 'Dependent', role: 'numeric', required: true },
      { key: 'covariates', kind: 'variables', label: 'Covariates', role: 'numeric', multiple: true, required: false },
      { key: 'factors', kind: 'variables', label: 'Factors', role: 'categorical', multiple: true, required: false },
      { key: 'interact', kind: 'toggle', label: 'Include first-pair interactions', default: false },
      { key: 'ciLevel', kind: 'number', label: 'CI level', min: 0.8, max: 0.99, step: 0.01, required: false },
    ],
  },
  {
    id: 'regression.logistic',
    module: 'regression',
    moduleLabel: 'Regression',
    title: 'Logistic Regression',
    description: 'Binomial, multinomial, and proportional-odds ordinal logit. Bayesian logistic arrives in Phase 4.',
    phase: 3,
    implemented: true,
    frequentist: true,
    bayesian: false,
    fields: [
      { key: 'dependent', kind: 'select', label: 'Dependent', role: 'any', required: true },
      { key: 'covariates', kind: 'variables', label: 'Covariates', role: 'numeric', multiple: true, required: false },
      { key: 'factors', kind: 'variables', label: 'Factors', role: 'categorical', multiple: true, required: false },
      { key: 'model', kind: 'choice', label: 'Model', required: true, options: [{ value: 'binomial', label: 'Binomial' }, { value: 'multinomial', label: 'Multinomial' }, { value: 'ordinal', label: 'Ordinal (proportional odds)' }] },
    ],
  },
  {
    id: 'regression.glm',
    module: 'regression',
    moduleLabel: 'Regression',
    title: 'Generalized Linear Model',
    description: 'Gaussian, binomial, Poisson, gamma, inverse-Gaussian, and negative-binomial GLMs.',
    phase: 3,
    implemented: true,
    frequentist: true,
    bayesian: false,
    fields: [
      { key: 'dependent', kind: 'select', label: 'Dependent', role: 'numeric', required: true },
      { key: 'covariates', kind: 'variables', label: 'Covariates', role: 'numeric', multiple: true, required: false },
      { key: 'factors', kind: 'variables', label: 'Factors', role: 'categorical', multiple: true, required: false },
      { key: 'family', kind: 'choice', label: 'Family', required: true, options: [
        { value: 'gaussian', label: 'Gaussian' },
        { value: 'binomial', label: 'Binomial' },
        { value: 'poisson', label: 'Poisson' },
        { value: 'gamma', label: 'Gamma' },
        { value: 'inverse.gaussian', label: 'Inverse Gaussian' },
        { value: 'negbin', label: 'Negative binomial' },
      ] },
    ],
  },
  {
    id: 'frequencies.binomial',
    module: 'frequencies',
    moduleLabel: 'Frequencies',
    title: 'Binomial Test',
    description: 'Exact, mid-p, and Wald tests with Wilson intervals. Bayesian binomial arrives in Phase 4.',
    phase: 3,
    implemented: true,
    frequentist: true,
    bayesian: false,
    fields: [
      { key: 'variable', kind: 'select', label: 'Variable', role: 'categorical', required: true },
      { key: 'p0', kind: 'number', label: 'Test value p₀', min: 0, max: 1, step: 0.01, required: true, default: 0.5 },
    ],
  },
  {
    id: 'frequencies.multinomial',
    module: 'frequencies',
    moduleLabel: 'Frequencies',
    title: 'Multinomial Test',
    description: 'Equal-probability multinomial goodness of fit. Informed Bayesian multinomial arrives in Phase 4.',
    phase: 3,
    implemented: true,
    frequentist: true,
    bayesian: false,
    fields: [
      { key: 'variable', kind: 'select', label: 'Variable', role: 'categorical', required: true },
    ],
  },
  {
    id: 'frequencies.contingency',
    module: 'frequencies',
    moduleLabel: 'Frequencies',
    title: 'Contingency Tables',
    description: 'Pearson, likelihood-ratio, Fisher (2×2), McNemar, odds/risk ratios, optional CMH. Bayesian tables arrive in Phase 4.',
    phase: 3,
    implemented: true,
    frequentist: true,
    bayesian: false,
    fields: [
      { key: 'rows', kind: 'select', label: 'Rows', role: 'categorical', required: true },
      { key: 'columns', kind: 'select', label: 'Columns', role: 'categorical', required: true },
      { key: 'stratum', kind: 'select', label: 'Stratum (CMH)', role: 'categorical', required: false },
    ],
  },
  {
    id: 'frequencies.loglinear',
    module: 'frequencies',
    moduleLabel: 'Frequencies',
    title: 'Log-Linear Regression',
    description: 'Poisson log-linear model of aggregated multiway tables.',
    phase: 3,
    implemented: true,
    frequentist: true,
    bayesian: false,
    fields: [
      { key: 'rows', kind: 'select', label: 'Factor 1', role: 'categorical', required: true },
      { key: 'columns', kind: 'select', label: 'Factor 2', role: 'categorical', required: true },
      { key: 'stratum', kind: 'select', label: 'Factor 3 (optional)', role: 'categorical', required: false },
    ],
  },
  {
    id: 'factor.pca',
    module: 'factor',
    moduleLabel: 'Factor',
    title: 'Principal Component Analysis',
    description: 'Loadings, scores, biplot, and Horn parallel analysis.',
    phase: 3,
    implemented: true,
    frequentist: true,
    bayesian: false,
    fields: [
      { key: 'variables', kind: 'variables', label: 'Variables', role: 'numeric', multiple: true, required: true },
      { key: 'matrix', kind: 'choice', label: 'Matrix', required: true, options: [{ value: 'correlation', label: 'Correlation' }, { value: 'covariance', label: 'Covariance' }] },
      { key: 'nComponents', kind: 'number', label: 'Components (0 = Kaiser/PA)', min: 0, max: 20, step: 1, required: false, default: 0 },
    ],
  },
  {
    id: 'factor.efa',
    module: 'factor',
    moduleLabel: 'Factor',
    title: 'Exploratory Factor Analysis',
    description: 'PAF or approximate ML with none/varimax/promax rotation. CFA is a separate analysis.',
    phase: 3,
    implemented: true,
    frequentist: true,
    bayesian: false,
    fields: [
      { key: 'variables', kind: 'variables', label: 'Variables', role: 'numeric', multiple: true, required: true },
      { key: 'nFactors', kind: 'number', label: 'Factors', min: 1, max: 12, step: 1, required: true, default: 1 },
      { key: 'method', kind: 'choice', label: 'Extraction', required: true, options: [{ value: 'paf', label: 'Principal axis' }, { value: 'ml', label: 'Approximate ML' }] },
      { key: 'rotation', kind: 'choice', label: 'Rotation', required: true, options: [{ value: 'varimax', label: 'Varimax' }, { value: 'promax', label: 'Promax' }, { value: 'none', label: 'None' }] },
    ],
  },
  {
    id: 'reliability.unidimensional',
    module: 'reliability',
    moduleLabel: 'Reliability',
    title: 'Unidimensional Reliability',
    description: 'Cronbach α, McDonald ω, Guttman λ₆, Spearman–Brown. Bayesian reliability arrives in Phase 4.',
    phase: 3,
    implemented: true,
    frequentist: true,
    bayesian: false,
    fields: [
      { key: 'variables', kind: 'variables', label: 'Items', role: 'numeric', multiple: true, required: true },
    ],
  },
  {
    id: 'reliability.icc',
    module: 'reliability',
    moduleLabel: 'Reliability',
    title: 'Intraclass Correlation',
    description: 'Shrout–Fleiss / McGraw–Wong ICC(1), ICC(2), ICC(3) single and average forms.',
    phase: 3,
    implemented: true,
    frequentist: true,
    bayesian: false,
    fields: [
      { key: 'variables', kind: 'variables', label: 'Raters / measures', role: 'numeric', multiple: true, required: true },
    ],
  },
  {
    id: 'reliability.agreement',
    module: 'reliability',
    moduleLabel: 'Reliability',
    title: 'Rater Agreement',
    description: 'Cohen’s κ, Fleiss’ κ, and interval Krippendorff’s α.',
    phase: 3,
    implemented: true,
    frequentist: true,
    bayesian: false,
    fields: [
      { key: 'raters', kind: 'variables', label: 'Rater columns', role: 'categorical', multiple: true, required: true },
    ],
  },
  {
    id: 'reliability.blandAltman',
    module: 'reliability',
    moduleLabel: 'Reliability',
    title: 'Bland–Altman Plots',
    description: 'Mean-difference plot with 95% limits of agreement.',
    phase: 3,
    implemented: true,
    frequentist: true,
    bayesian: false,
    fields: [
      { key: 'measure1', kind: 'select', label: 'Measure 1', role: 'numeric', required: true },
      { key: 'measure2', kind: 'select', label: 'Measure 2', role: 'numeric', required: true },
    ],
  },
]

const RAW_CATALOG: AnalysisDef[] = [
  ...descriptives,
  ...phase2,
  {
    id: 'mixed.lmm',
    module: 'mixedModels',
    moduleLabel: 'Mixed Models',
    title: 'Linear Mixed Models',
    description: 'Random-intercept LMM with GLS fixed effects, EM variances, and BLUPs.',
    phase: 5,
    implemented: true,
    frequentist: true,
    bayesian: true,
    fields: [
      { key: 'dependent', kind: 'select', label: 'Dependent', role: 'numeric', required: true },
      { key: 'cluster', kind: 'select', label: 'Clustering factor', role: 'categorical', required: true },
      { key: 'covariates', kind: 'variables', label: 'Covariates', role: 'numeric', multiple: true, required: false },
      { key: 'factors', kind: 'variables', label: 'Fixed factors', role: 'categorical', multiple: true, required: false },
      { key: 'interact', kind: 'toggle', label: 'Fixed-factor interactions', default: false },
    ],
  },
  {
    id: 'mixed.glmm',
    module: 'mixedModels',
    moduleLabel: 'Mixed Models',
    title: 'Generalized Linear Mixed Models',
    description: 'PQL GLMM with a random intercept (binomial, Poisson, Gaussian).',
    phase: 5,
    implemented: true,
    frequentist: true,
    bayesian: true,
    fields: [
      { key: 'dependent', kind: 'select', label: 'Dependent', role: 'any', required: true },
      { key: 'cluster', kind: 'select', label: 'Clustering factor', role: 'categorical', required: true },
      { key: 'covariates', kind: 'variables', label: 'Covariates', role: 'numeric', multiple: true, required: false },
      { key: 'factors', kind: 'variables', label: 'Fixed factors', role: 'categorical', multiple: true, required: false },
      { key: 'family', kind: 'choice', label: 'Family', required: true, options: [
        { value: 'binomial', label: 'Binomial' },
        { value: 'poisson', label: 'Poisson' },
        { value: 'gaussian', label: 'Gaussian' },
      ] },
    ],
  },
  ...phase3,
  {
    id: 'factor.cfa',
    module: 'factor',
    moduleLabel: 'Factor',
    title: 'Confirmatory Factor Analysis',
    description: 'Congeneric ML CFA with simple-structure loadings. Frequentist and Bayesian modes share this analysis.',
    phase: 6,
    implemented: true,
    frequentist: true,
    bayesian: true,
    fields: [
      { key: 'variables', kind: 'variables', label: 'Indicators', role: 'numeric', multiple: true, required: true },
      { key: 'nFactors', kind: 'number', label: 'Factors', min: 1, max: 4, step: 1, required: true, default: 1 },
    ],
  },
  {
    id: 'acceptance.attribute',
    module: 'acceptanceSampling',
    moduleLabel: 'Acceptance Sampling',
    title: 'Attribute Sampling',
    description: 'Create and analyze binomial attribute plans (n, c), OC curve, accept/reject lots.',
    phase: 7,
    implemented: true,
    frequentist: true,
    bayesian: true,
    allowEmptyData: true,
    fields: [
      { key: 'n', kind: 'number', label: 'n', required: true, default: 50, min: 1, step: 1 },
      { key: 'c', kind: 'number', label: 'Acceptance number c', required: true, default: 1, min: 0, step: 1 },
      { key: 'aql', kind: 'number', label: 'AQL', required: true, default: 0.01, min: 0, max: 1, step: 0.001 },
      { key: 'ltpd', kind: 'number', label: 'LTPD', required: true, default: 0.06, min: 0, max: 1, step: 0.001 },
      { key: 'defects', kind: 'select', label: 'Observed defects (optional)', role: 'numeric', required: false },
      { key: 'observed', kind: 'number', label: 'Observed defects (if no column)', required: false, default: 0, min: 0, step: 1 },
    ],
  },
  {
    id: 'acceptance.variable',
    module: 'acceptanceSampling',
    moduleLabel: 'Acceptance Sampling',
    title: 'Variable Sampling',
    description: 'k-method variable sampling plans (unknown σ) vs a USL.',
    phase: 7,
    implemented: true,
    frequentist: true,
    bayesian: true,
    allowEmptyData: true,
    fields: [
      { key: 'variable', kind: 'select', label: 'Measurement', role: 'numeric', required: false },
      { key: 'usl', kind: 'number', label: 'USL', required: true, default: 10, step: 0.1 },
      { key: 'k', kind: 'number', label: 'k', required: true, default: 1.64, min: 0, step: 0.01 },
      { key: 'n', kind: 'number', label: 'n (if no column)', required: false, default: 20, min: 2, step: 1 },
      { key: 'mean', kind: 'number', label: 'x̄ (if no column)', required: false, default: 8, step: 0.1 },
      { key: 'sd', kind: 'number', label: 's / σ0 (if no column)', required: false, default: 1, min: 0.001, step: 0.01 },
    ],
  },
  {
    id: 'audit.sampling',
    module: 'audit',
    moduleLabel: 'Audit',
    title: 'Audit Sampling',
    description: 'Planning, selection size, taint evaluation, classical and Bayesian.',
    phase: 7,
    implemented: true,
    frequentist: true,
    bayesian: true,
    allowEmptyData: true,
    fields: [
      { key: 'N', kind: 'number', label: 'Population N', required: true, default: 1000, min: 1, step: 1 },
      { key: 'p', kind: 'number', label: 'Planning p', required: true, default: 0.05, min: 0, max: 1, step: 0.01 },
      { key: 'precision', kind: 'number', label: 'Precision e', required: true, default: 0.02, min: 0.001, step: 0.001 },
      { key: 'z', kind: 'number', label: 'z', required: false, default: 1.96, min: 0.5, step: 0.01 },
      { key: 'bookValue', kind: 'select', label: 'Book value', role: 'numeric', required: false },
      { key: 'auditValue', kind: 'select', label: 'Audit value', role: 'numeric', required: false },
      { key: 'observedRate', kind: 'number', label: 'Observed taint (if no columns)', required: false, default: 0, min: 0, max: 1, step: 0.01 },
    ],
  },
  {
    id: 'audit.data',
    module: 'audit',
    moduleLabel: 'Audit',
    title: 'Data Auditing',
    description: 'Benford first digits, repeated values, fairness (demographic parity).',
    phase: 7,
    implemented: true,
    frequentist: true,
    bayesian: true,
    fields: [
      { key: 'amount', kind: 'select', label: 'Amount', role: 'numeric', required: false },
      { key: 'group', kind: 'select', label: 'Group (fairness)', role: 'categorical', required: false },
      { key: 'outcome', kind: 'select', label: 'Outcome (fairness)', role: 'any', required: false },
    ],
  },
  {
    id: 'bain.tests',
    module: 'bain',
    moduleLabel: 'Bain',
    title: 'Bain',
    description: 'Informative hypotheses for t, ANOVA, regression, correlation, variances, and SEM.',
    phase: 6,
    implemented: true,
    frequentist: false,
    bayesian: true,
    fields: [
      { key: 'family', kind: 'choice', label: 'Family', required: true, options: [
        { value: 't', label: 'One-sample t' },
        { value: 'anova', label: 'ANOVA' },
        { value: 'regression', label: 'Linear regression' },
        { value: 'correlation', label: 'Correlation' },
        { value: 'variances', label: 'Variances' },
        { value: 'sem', label: 'SEM / CFA' },
      ] },
      { key: 'hypothesis', kind: 'choice', label: 'Hypothesis (t)', required: false, options: [
        { value: 'greater', label: 'μ > μ₀' },
        { value: 'less', label: 'μ < μ₀' },
        { value: 'equal', label: 'μ = μ₀' },
      ] },
      { key: 'variable', kind: 'select', label: 'Variable (t)', role: 'numeric', required: false },
      { key: 'mu0', kind: 'number', label: 'μ₀', required: false, default: 0, step: 0.1 },
      { key: 'dependent', kind: 'select', label: 'Dependent', role: 'numeric', required: false },
      { key: 'group', kind: 'select', label: 'Group', role: 'categorical', required: false },
      { key: 'predictors', kind: 'variables', label: 'Predictors', role: 'numeric', multiple: true, required: false },
      { key: 'x', kind: 'select', label: 'X (correlation)', role: 'numeric', required: false },
      { key: 'y', kind: 'select', label: 'Y (correlation)', role: 'numeric', required: false },
      { key: 'variables', kind: 'variables', label: 'SEM indicators', role: 'numeric', multiple: true, required: false },
      { key: 'nFactors', kind: 'number', label: 'SEM factors', required: false, default: 1, min: 1, step: 1 },
    ],
  },
  {
    id: 'bff.general',
    module: 'bayesFactorFunctions',
    moduleLabel: 'Bayes Factor Functions',
    title: 'Bayes Factor Functions',
    description: 'BF as a function of n for z, t, ANOVA, regression, and chi-square statistics.',
    phase: 4,
    implemented: true,
    frequentist: false,
    bayesian: true,
    allowEmptyData: true,
    fields: [
      { key: 'bffKind', kind: 'choice', label: 'Family', required: true, options: [
        { value: 't', label: 't' },
        { value: 'z', label: 'z' },
        { value: 'anova', label: 'ANOVA F' },
        { value: 'regression', label: 'Regression F' },
        { value: 'chi', label: 'Chi-square' },
      ] },
      { key: 'stat', kind: 'number', label: 'Observed statistic', required: true, default: 2, step: 0.1 },
      { key: 'n', kind: 'number', label: 'n at marker', required: true, default: 40, min: 4, step: 1 },
      { key: 'df', kind: 'number', label: 'df (t)', required: false, default: 20, min: 1, step: 1 },
      { key: 'df1', kind: 'number', label: 'df1 (ANOVA)', required: false, default: 2, min: 1, step: 1 },
      { key: 'rscale', kind: 'number', label: 'rscale', required: false, default: 0.707, min: 0.1, step: 0.01 },
    ],
  },
  {
    id: 'bfpack.constrained',
    module: 'bfpack',
    moduleLabel: 'BFpack',
    title: 'BFpack',
    description: 'Constrained hypotheses for t, ANOVA, regression, correlation, and variances. Frequentist and Bayesian modes share this analysis.',
    phase: 6,
    implemented: true,
    frequentist: true,
    bayesian: true,
    fields: [
      { key: 'family', kind: 'choice', label: 'Family', required: true, options: [
        { value: 't', label: 'One-sample t' },
        { value: 'anova', label: 'ANOVA' },
        { value: 'regression', label: 'Linear regression' },
        { value: 'correlation', label: 'Correlation' },
        { value: 'variances', label: 'Variances' },
      ] },
      { key: 'hypothesis', kind: 'choice', label: 'Hypothesis (t)', required: false, options: [
        { value: 'greater', label: 'μ > μ₀' },
        { value: 'less', label: 'μ < μ₀' },
        { value: 'equal', label: 'μ = μ₀' },
      ] },
      { key: 'variable', kind: 'select', label: 'Variable (t)', role: 'numeric', required: false },
      { key: 'mu0', kind: 'number', label: 'μ₀', required: false, default: 0, step: 0.1 },
      { key: 'dependent', kind: 'select', label: 'Dependent', role: 'numeric', required: false },
      { key: 'group', kind: 'select', label: 'Group', role: 'categorical', required: false },
      { key: 'predictors', kind: 'variables', label: 'Predictors', role: 'numeric', multiple: true, required: false },
      { key: 'x', kind: 'select', label: 'X (correlation)', role: 'numeric', required: false },
      { key: 'y', kind: 'select', label: 'Y (correlation)', role: 'numeric', required: false },
    ],
  },
  {
    id: 'bsts.model',
    module: 'bsts',
    moduleLabel: 'BSTS',
    title: 'Bayesian Structural Time Series',
    description: 'Local-level Kalman state space with optional seasonal means.',
    phase: 5,
    implemented: true,
    frequentist: false,
    bayesian: true,
    fields: [
      { key: 'variable', kind: 'select', label: 'Series', role: 'numeric', required: true },
      { key: 'period', kind: 'number', label: 'Seasonal period (0 = none)', required: false, default: 0, min: 0, step: 1 },
      { key: 'horizon', kind: 'number', label: 'Forecast horizon', required: true, default: 8, min: 1, step: 1 },
    ],
  },
  {
    id: 'circular.descriptives',
    module: 'circular',
    moduleLabel: 'Circular Statistics',
    title: 'Circular Descriptives',
    description: 'Mean direction, resultant length, circular SD, and von Mises concentration.',
    phase: 5,
    implemented: true,
    frequentist: true,
    bayesian: false,
    fields: [
      { key: 'variable', kind: 'select', label: 'Angle', role: 'numeric', required: true },
      { key: 'angleUnit', kind: 'choice', label: 'Unit', required: true, options: [{ value: 'degrees', label: 'Degrees' }, { value: 'radians', label: 'Radians' }] },
    ],
  },
  {
    id: 'circular.tests',
    module: 'circular',
    moduleLabel: 'Circular Statistics',
    title: 'Circular Hypothesis Tests',
    description: 'Rayleigh uniformity, V-test, and Watson–Williams multi-sample test.',
    phase: 5,
    implemented: true,
    frequentist: true,
    bayesian: false,
    fields: [
      { key: 'variable', kind: 'select', label: 'Angle', role: 'numeric', required: true },
      { key: 'group', kind: 'select', label: 'Grouping (optional)', role: 'categorical', required: false },
      { key: 'angleUnit', kind: 'choice', label: 'Unit', required: true, options: [{ value: 'degrees', label: 'Degrees' }, { value: 'radians', label: 'Radians' }] },
      { key: 'mu0', kind: 'number', label: 'Specified mean (V-test)', required: false, default: 0, step: 1 },
    ],
  },
  {
    id: 'cochrane.ma',
    module: 'cochrane',
    moduleLabel: 'Cochrane Meta-Analyses',
    title: 'Cochrane Meta-Analyses',
    description: 'Continuous and dichotomous meta-analysis (same engine as Meta-Analysis) with Cochrane field presets.',
    phase: 6,
    implemented: true,
    frequentist: true,
    bayesian: true,
    fields: [
      { key: 'yi', kind: 'select', label: 'Effect (yi)', role: 'numeric', required: false },
      { key: 'sei', kind: 'select', label: 'SE (sei)', role: 'numeric', required: false },
      { key: 'study', kind: 'select', label: 'Study label', role: 'any', required: false },
      { key: 'n1', kind: 'select', label: 'n (arm 1)', role: 'numeric', required: false },
      { key: 'mean1', kind: 'select', label: 'Mean (arm 1)', role: 'numeric', required: false },
      { key: 'sd1', kind: 'select', label: 'SD (arm 1)', role: 'numeric', required: false },
      { key: 'n2', kind: 'select', label: 'n (arm 2)', role: 'numeric', required: false },
      { key: 'mean2', kind: 'select', label: 'Mean (arm 2)', role: 'numeric', required: false },
      { key: 'sd2', kind: 'select', label: 'SD (arm 2)', role: 'numeric', required: false },
      { key: 'events1', kind: 'select', label: 'Events (arm 1)', role: 'numeric', required: false },
      { key: 'nonevents1', kind: 'select', label: 'Non-events (arm 1)', role: 'numeric', required: false },
      { key: 'events2', kind: 'select', label: 'Events (arm 2)', role: 'numeric', required: false },
      { key: 'nonevents2', kind: 'select', label: 'Non-events (arm 2)', role: 'numeric', required: false },
    ],
  },
  {
    id: 'distributions.explorer',
    module: 'distributions',
    moduleLabel: 'Distributions',
    title: 'Distribution Families',
    description: 'Compare JASP-list families (including skew-normal, Wald, ZIP/ZINB, mixtures, stretched beta) with KS / chi-square GOF.',
    phase: 7,
    implemented: true,
    frequentist: true,
    bayesian: true,
    fields: [
      { key: 'variable', kind: 'select', label: 'Variable', role: 'numeric', required: true },
      { key: 'family', kind: 'choice', label: 'Family', required: true, options: [
        { value: 'auto', label: 'Auto-rank' },
        { value: 'normal', label: 'Normal' },
        { value: 'skew_normal', label: 'Skew-normal' },
        { value: 'laplace', label: 'Laplace' },
        { value: 'gumbel', label: 'Gumbel' },
        { value: 'inverse_gaussian', label: 'Wald' },
        { value: 'stretched_beta', label: 'Stretched beta' },
        { value: 'mixture_normal', label: 'Normal mixture' },
        { value: 'poisson', label: 'Poisson' },
        { value: 'zip', label: 'ZIP' },
        { value: 'zinb', label: 'ZINB' },
        { value: 'weibull', label: 'Weibull' },
        { value: 'gamma', label: 'Gamma' },
        { value: 'beta', label: 'Beta' },
      ] },
    ],
  },
  {
    id: 'equivalence.t',
    module: 'equivalence',
    moduleLabel: 'Equivalence T-Tests',
    title: 'Equivalence T-Tests',
    description: 'TOST for independent, paired, and one-sample mean differences. Bayesian equivalence arrives in Phase 4.',
    phase: 2,
    implemented: true,
    frequentist: true,
    bayesian: false,
    fields: [
      { key: 'design', kind: 'choice', label: 'Design', required: true, options: [
        { value: 'independent', label: 'Independent samples' },
        { value: 'paired', label: 'Paired samples' },
        { value: 'one-sample', label: 'One sample' },
      ] },
      { key: 'dependent', kind: 'select', label: 'Dependent (independent)', role: 'numeric', required: false },
      { key: 'group', kind: 'select', label: 'Grouping variable (independent)', role: 'categorical', required: false },
      { key: 'measure1', kind: 'select', label: 'Measure 1 (paired)', role: 'numeric', required: false },
      { key: 'measure2', kind: 'select', label: 'Measure 2 (paired)', role: 'numeric', required: false },
      { key: 'variable', kind: 'select', label: 'Variable (one-sample)', role: 'numeric', required: false },
      { key: 'mu0', kind: 'number', label: 'Test value (one-sample)', required: false, default: 0, step: 0.1 },
      { key: 'delta', kind: 'number', label: 'Equivalence bound Δ', required: true, default: 0.5, min: 0, step: 0.05 },
      { key: 'alpha', kind: 'number', label: 'α', required: true, default: 0.05, min: 0.001, max: 0.2, step: 0.01 },
      { key: 'equalVariance', kind: 'toggle', label: 'Equal variances (independent Student)', default: false },
    ],
  },
  {
    id: 'jags.model',
    module: 'jags',
    moduleLabel: 'JAGS',
    title: 'JAGS',
    description: 'Canonical Gibbs models with trace, density, ACF, R̂, and ESS. In-browser conjugate MCMC, not JAGS WASM.',
    phase: 6,
    implemented: true,
    frequentist: false,
    bayesian: true,
    allowEmptyData: true,
    fields: [
      { key: 'jagsKind', kind: 'choice', label: 'Model', required: true, options: [
        { value: 'normalMean', label: 'Normal mean' },
        { value: 'regression', label: 'Simple regression' },
        { value: 'binomial', label: 'Binomial p' },
      ] },
      { key: 'variable', kind: 'select', label: 'Variable (normal / Bernoulli)', role: 'numeric', required: false },
      { key: 'dependent', kind: 'select', label: 'Dependent (regression)', role: 'numeric', required: false },
      { key: 'predictor', kind: 'select', label: 'Predictor (regression)', role: 'numeric', required: false },
      { key: 'successes', kind: 'number', label: 'Successes (binomial)', required: false, default: 6, min: 0, step: 1 },
      { key: 'trials', kind: 'number', label: 'Trials (binomial)', required: false, default: 10, min: 1, step: 1 },
      { key: 'priorAlpha', kind: 'number', label: 'Beta α', required: false, default: 1, min: 0.1, step: 0.1 },
      { key: 'priorBeta', kind: 'number', label: 'Beta β', required: false, default: 1, min: 0.1, step: 0.1 },
      { key: 'nIter', kind: 'number', label: 'Iterations', required: false, default: 800, min: 200, step: 50 },
      { key: 'nChains', kind: 'number', label: 'Chains', required: false, default: 2, min: 2, max: 4, step: 1 },
      { key: 'burnin', kind: 'number', label: 'Burn-in', required: false, default: 200, min: 50, step: 10 },
      { key: 'seed', kind: 'number', label: 'Seed', required: false, default: 1, min: 1, step: 1 },
    ],
  },
  {
    id: 'learnBayes.labs',
    module: 'learnBayes',
    moduleLabel: 'Learn Bayes',
    title: 'Learn Bayes',
    description: 'Binomial updating, binary classification, and Buffon’s needle on the shared Bayesian engine.',
    phase: 4,
    implemented: true,
    frequentist: false,
    bayesian: true,
    allowEmptyData: true,
    fields: [
      { key: 'lab', kind: 'choice', label: 'Lab', required: true, options: [
        { value: 'binomial', label: 'Binomial estimation / testing' },
        { value: 'classification', label: 'Binary classification' },
        { value: 'buffon', label: 'Buffon’s needle' },
      ] },
      { key: 'priorAlpha', kind: 'number', label: 'Prior α', required: false, default: 2, min: 0.1, step: 0.1 },
      { key: 'priorBeta', kind: 'number', label: 'Prior β', required: false, default: 2, min: 0.1, step: 0.1 },
      { key: 'successes', kind: 'number', label: 'Successes', required: false, default: 6, min: 0, step: 1 },
      { key: 'trials', kind: 'number', label: 'Trials', required: false, default: 10, min: 1, step: 1 },
      { key: 'baseRate', kind: 'number', label: 'Base rate', required: false, default: 0.02, min: 0, max: 1, step: 0.01 },
      { key: 'sens', kind: 'number', label: 'Sensitivity', required: false, default: 0.95, min: 0, max: 1, step: 0.01 },
      { key: 'fpr', kind: 'number', label: 'False-positive rate', required: false, default: 0.05, min: 0, max: 1, step: 0.01 },
      { key: 'needle', kind: 'number', label: 'Needle length', required: false, default: 1, min: 0.1, step: 0.1 },
      { key: 'floor', kind: 'number', label: 'Floor spacing', required: false, default: 2, min: 0.2, step: 0.1 },
    ],
  },
  {
    id: 'learnStats.labs',
    module: 'learnStats',
    moduleLabel: 'Learn Stats',
    title: 'Learn Stats',
    description: 'Normal, binomial, CLT, SE, descriptives, sample variability, p-values, CIs, effect sizes, and the test decision tree — all on the Phase 1–2 engines.',
    phase: 8,
    implemented: true,
    frequentist: true,
    bayesian: false,
    allowEmptyData: true,
    fields: [
      { key: 'lab', kind: 'choice', label: 'Lab', required: true, options: [
        { value: 'normal', label: 'Normal samples' },
        { value: 'binomial', label: 'Binomial' },
        { value: 'clt', label: 'Central limit theorem' },
        { value: 'se', label: 'Standard error' },
        { value: 'descriptives', label: 'Descriptive statistics' },
        { value: 'variability', label: 'Sample variability' },
        { value: 'pvalue', label: 'p-values' },
        { value: 'ci', label: 'Confidence intervals' },
        { value: 'effect', label: 'Effect sizes' },
        { value: 'tree', label: 'Statistical test decision tree' },
      ] },
      { key: 'n', kind: 'number', label: 'n (simulated)', required: false, default: 40, min: 8, step: 1 },
      { key: 'mu', kind: 'number', label: 'μ', required: false, default: 0, step: 0.1 },
      { key: 'sigma', kind: 'number', label: 'σ', required: false, default: 1, min: 0.01, step: 0.1 },
      { key: 'p', kind: 'number', label: 'Binomial π', required: false, default: 0.5, min: 0, max: 1, step: 0.01 },
      { key: 'mu0', kind: 'number', label: 'Test value μ₀', required: false, default: 0, step: 0.1 },
      { key: 'effectSize', kind: 'number', label: 'Cohen’s d (effect lab)', required: false, default: 0.8, min: 0, step: 0.1 },
      { key: 'seed', kind: 'number', label: 'Seed', required: false, default: 1, min: 1, step: 1 },
      { key: 'outcomeType', kind: 'choice', label: 'Tree: outcome', required: false, options: [
        { value: 'numeric', label: 'Numeric' },
        { value: 'categorical', label: 'Categorical' },
      ] },
      { key: 'groups', kind: 'choice', label: 'Tree: groups', required: false, options: [
        { value: 'one', label: 'One' },
        { value: 'two', label: 'Two' },
        { value: 'many', label: 'Three or more' },
      ] },
      { key: 'paired', kind: 'toggle', label: 'Tree: paired / repeated', default: false },
      { key: 'predictors', kind: 'choice', label: 'Tree: predictors', required: false, options: [
        { value: 'none', label: 'None' },
        { value: 'one', label: 'One' },
        { value: 'many', label: 'Several' },
      ] },
      { key: 'variable', kind: 'select', label: 'Optional data column', role: 'any', required: false },
    ],
  },
  {
    id: 'ml.regression',
    module: 'machineLearning',
    moduleLabel: 'Machine Learning',
    title: 'ML Regression',
    description: 'Boosting, trees, KNN, linear, NN, RF, regularized linear, SVM.',
    phase: 7,
    implemented: true,
    frequentist: true,
    bayesian: false,
    fields: [
      { key: 'dependent', kind: 'select', label: 'Dependent', role: 'numeric', required: true },
      { key: 'predictors', kind: 'variables', label: 'Predictors', role: 'numeric', multiple: true, required: true },
      { key: 'algorithm', kind: 'choice', label: 'Algorithm', required: true, options: [
        { value: 'linear', label: 'Linear' },
        { value: 'regularized', label: 'Ridge' },
        { value: 'lasso', label: 'Lasso' },
        { value: 'knn', label: 'KNN' },
        { value: 'tree', label: 'Decision tree' },
        { value: 'forest', label: 'Random forest' },
        { value: 'boosting', label: 'Boosting' },
        { value: 'nn', label: 'Neural net' },
        { value: 'svm', label: 'SVM (linear)' },
      ] },
    ],
  },
  {
    id: 'ml.classification',
    module: 'machineLearning',
    moduleLabel: 'Machine Learning',
    title: 'ML Classification',
    description: 'Boosting, tree, KNN, LDA, logistic, naive Bayes, NN, RF, SVM.',
    phase: 7,
    implemented: true,
    frequentist: true,
    bayesian: false,
    fields: [
      { key: 'dependent', kind: 'select', label: 'Dependent', role: 'any', required: true },
      { key: 'predictors', kind: 'variables', label: 'Predictors', role: 'numeric', multiple: true, required: true },
      { key: 'algorithm', kind: 'choice', label: 'Algorithm', required: true, options: [
        { value: 'logistic', label: 'Logistic' },
        { value: 'lda', label: 'LDA' },
        { value: 'nb', label: 'Naive Bayes' },
        { value: 'knn', label: 'KNN' },
        { value: 'tree', label: 'Decision tree' },
        { value: 'forest', label: 'Random forest' },
        { value: 'boosting', label: 'Boosting' },
        { value: 'nn', label: 'Neural net' },
        { value: 'svm', label: 'SVM (linear)' },
      ] },
    ],
  },
  {
    id: 'ml.clustering',
    module: 'machineLearning',
    moduleLabel: 'Machine Learning',
    title: 'ML Clustering',
    description: 'K-means, DBSCAN, hierarchical, fuzzy C-means, GMM, neighborhood, RF-proximity stand-in.',
    phase: 7,
    implemented: true,
    frequentist: true,
    bayesian: false,
    fields: [
      { key: 'variables', kind: 'variables', label: 'Features', role: 'numeric', multiple: true, required: true },
      { key: 'algorithm', kind: 'choice', label: 'Algorithm', required: true, options: [
        { value: 'kmeans', label: 'K-means' },
        { value: 'dbscan', label: 'DBSCAN' },
        { value: 'hierarchical', label: 'Hierarchical' },
        { value: 'fuzzy', label: 'Fuzzy C-means' },
        { value: 'gmm', label: 'Model-based (GMM)' },
        { value: 'neighborhood', label: 'Neighborhood' },
        { value: 'rf', label: 'Random forest' },
      ] },
      { key: 'k', kind: 'number', label: 'k', required: false, default: 3, min: 2, max: 8, step: 1 },
      { key: 'eps', kind: 'number', label: 'DBSCAN ε', required: false, default: 0.6, min: 0.05, step: 0.05 },
      { key: 'minPts', kind: 'number', label: 'DBSCAN minPts', required: false, default: 4, min: 2, step: 1 },
    ],
  },
  {
    id: 'ml.prediction',
    module: 'machineLearning',
    moduleLabel: 'Machine Learning',
    title: 'ML Prediction',
    description: 'Train on the head of the table and score the holdout tail as new cases.',
    phase: 7,
    implemented: true,
    frequentist: true,
    bayesian: false,
    fields: [
      { key: 'dependent', kind: 'select', label: 'Dependent', role: 'any', required: true },
      { key: 'predictors', kind: 'variables', label: 'Predictors', role: 'numeric', multiple: true, required: true },
      { key: 'algorithm', kind: 'choice', label: 'Algorithm', required: true, options: [
        { value: 'linear', label: 'Linear' },
        { value: 'ridge', label: 'Ridge' },
        { value: 'lasso', label: 'Lasso' },
        { value: 'knn', label: 'KNN' },
        { value: 'tree', label: 'Tree' },
        { value: 'boosting', label: 'Boosting' },
        { value: 'nn', label: 'Neural net' },
      ] },
      { key: 'task', kind: 'choice', label: 'Task', required: true, options: [
        { value: 'regression', label: 'Regression' },
        { value: 'classification', label: 'Classification' },
      ] },
      { key: 'holdout', kind: 'number', label: 'Holdout fraction', required: false, default: 0.3, min: 0.1, max: 0.5, step: 0.05 },
    ],
  },
  {
    id: 'meta.analysis',
    module: 'metaAnalysis',
    moduleLabel: 'Meta-Analysis',
    title: 'Meta-Analysis',
    description: 'FE/RE (DL), funnel, MH/Peto, PET-PEESE, WAAP-WLS, and conjugate Bayesian MA.',
    phase: 6,
    implemented: true,
    frequentist: true,
    bayesian: true,
    fields: [
      { key: 'yi', kind: 'select', label: 'Effect (yi)', role: 'numeric', required: false },
      { key: 'sei', kind: 'select', label: 'SE (sei)', role: 'numeric', required: false },
      { key: 'study', kind: 'select', label: 'Study label', role: 'any', required: false },
      { key: 'n1', kind: 'select', label: 'n (group 1)', role: 'numeric', required: false },
      { key: 'mean1', kind: 'select', label: 'Mean (group 1)', role: 'numeric', required: false },
      { key: 'sd1', kind: 'select', label: 'SD (group 1)', role: 'numeric', required: false },
      { key: 'n2', kind: 'select', label: 'n (group 2)', role: 'numeric', required: false },
      { key: 'mean2', kind: 'select', label: 'Mean (group 2)', role: 'numeric', required: false },
      { key: 'sd2', kind: 'select', label: 'SD (group 2)', role: 'numeric', required: false },
      { key: 'events1', kind: 'select', label: 'Events (group 1)', role: 'numeric', required: false },
      { key: 'nonevents1', kind: 'select', label: 'Non-events (group 1)', role: 'numeric', required: false },
      { key: 'events2', kind: 'select', label: 'Events (group 2)', role: 'numeric', required: false },
      { key: 'nonevents2', kind: 'select', label: 'Non-events (group 2)', role: 'numeric', required: false },
    ],
  },
  {
    id: 'network.psych',
    module: 'network',
    moduleLabel: 'Network',
    title: 'Network Analysis',
    description: 'Ridge Gaussian graphical models (partial correlations) with frequentist or Wishart-ridge Bayesian precision.',
    phase: 6,
    implemented: true,
    frequentist: true,
    bayesian: true,
    fields: [
      { key: 'variables', kind: 'variables', label: 'Nodes', role: 'numeric', multiple: true, required: true },
      { key: 'rho', kind: 'number', label: 'Ridge ρ', required: false, default: 0.1, min: 0, max: 2, step: 0.01 },
    ],
  },
  {
    id: 'power.analysis',
    module: 'power',
    moduleLabel: 'Power',
    title: 'Power Analysis',
    description: 'Sample size and power for t, ANOVA, two proportions, correlation, and linear regression.',
    phase: 2,
    implemented: true,
    frequentist: true,
    bayesian: false,
    allowEmptyData: true,
    fields: [
      { key: 'design', kind: 'choice', label: 'Design', required: true, options: [
        { value: 't.independent', label: 'Independent-samples t' },
        { value: 't.paired', label: 'Paired t' },
        { value: 't.oneSample', label: 'One-sample t' },
        { value: 'anova', label: 'One-way ANOVA' },
        { value: 'proportions', label: 'Two proportions' },
        { value: 'correlation', label: 'Correlation' },
        { value: 'regression', label: 'Linear regression' },
      ] },
      { key: 'compute', kind: 'choice', label: 'Solve for', required: true, options: [
        { value: 'n', label: 'Sample size' },
        { value: 'power', label: 'Power' },
      ] },
      { key: 'effectSize', kind: 'number', label: 'Effect size (d, f, h, ρ, or f²)', required: true, default: 0.5, step: 0.05 },
      { key: 'alpha', kind: 'number', label: 'α', required: true, default: 0.05, min: 0.001, max: 0.2, step: 0.01 },
      { key: 'power', kind: 'number', label: 'Target power', required: true, default: 0.8, min: 0.5, max: 0.99, step: 0.01 },
      { key: 'n', kind: 'number', label: 'n (when solving for power)', required: false, default: 64, min: 3, step: 1 },
      { key: 'groups', kind: 'number', label: 'ANOVA groups', required: false, default: 3, min: 2, step: 1 },
      { key: 'predictors', kind: 'number', label: 'Regression predictors', required: false, default: 1, min: 1, step: 1 },
      { key: 'alternative', kind: 'choice', label: 'Alternative (t / proportions / r)', required: true, options: alt },
    ],
  },
  {
    id: 'predictive.analytics',
    module: 'predictiveAnalytics',
    moduleLabel: 'Predictive Analytics',
    title: 'Predictive Analytics',
    description: 'Holdout scoring for linear, logistic, and Holt-trend forecasts.',
    phase: 5,
    implemented: true,
    frequentist: true,
    bayesian: false,
    fields: [
      { key: 'predKind', kind: 'choice', label: 'Workflow', required: true, options: [
        { value: 'linear', label: 'Linear regression holdout' },
        { value: 'logistic', label: 'Logistic holdout' },
        { value: 'forecast', label: 'Holt series forecast' },
      ] },
      { key: 'dependent', kind: 'select', label: 'Outcome / series', role: 'numeric', required: true },
      { key: 'covariates', kind: 'variables', label: 'Predictors', role: 'numeric', multiple: true, required: false },
      { key: 'holdout', kind: 'number', label: 'Holdout fraction', required: true, default: 0.3, min: 0.15, max: 0.5, step: 0.05 },
    ],
  },
  {
    id: 'process.model',
    module: 'process',
    moduleLabel: 'Process',
    title: 'PROCESS',
    description: 'Hayes models 1, 4, and 7 (moderation, mediation, index of moderated mediation).',
    phase: 5,
    implemented: true,
    frequentist: true,
    bayesian: true,
    fields: [
      { key: 'processModel', kind: 'choice', label: 'Hayes model', required: true, options: [
        { value: '4', label: '4 Mediation' },
        { value: '1', label: '1 Moderation' },
        { value: '7', label: '7 First-stage moderated mediation' },
      ] },
      { key: 'y', kind: 'select', label: 'Y', role: 'numeric', required: true },
      { key: 'x', kind: 'select', label: 'X', role: 'numeric', required: true },
      { key: 'm', kind: 'select', label: 'M (mediator)', role: 'numeric', required: false },
      { key: 'w', kind: 'select', label: 'W (moderator)', role: 'numeric', required: false },
    ],
  },
  {
    id: 'prophet.forecast',
    module: 'prophet',
    moduleLabel: 'Prophet',
    title: 'Prophet',
    description: 'Additive trend + Fourier seasonality (Taylor–Letham design, OLS).',
    phase: 5,
    implemented: true,
    frequentist: false,
    bayesian: true,
    fields: [
      { key: 'variable', kind: 'select', label: 'Series', role: 'numeric', required: true },
      { key: 'period', kind: 'number', label: 'Seasonal period', required: true, default: 12, min: 2, step: 1 },
      { key: 'fourier', kind: 'number', label: 'Fourier pairs', required: true, default: 3, min: 1, max: 6, step: 1 },
      { key: 'horizon', kind: 'number', label: 'Forecast horizon', required: true, default: 8, min: 1, step: 1 },
    ],
  },
  {
    id: 'qc.msa',
    module: 'qualityControl',
    moduleLabel: 'Quality Control',
    title: 'Measurement Systems Analysis',
    description: 'Type 1–4 MSA, gauge R&R, attributes agreement, test–retest.',
    phase: 7,
    implemented: true,
    frequentist: true,
    bayesian: false,
    fields: [
      { key: 'msaKind', kind: 'choice', label: 'Study', required: true, options: [
        { value: 'type1', label: 'Type 1 / test–retest' },
        { value: 'grr', label: 'Gauge R&R (Type 2–4)' },
      ] },
      { key: 'measurement', kind: 'select', label: 'Measurement', role: 'numeric', required: true },
      { key: 'reference', kind: 'number', label: 'Reference (Type 1)', required: false, default: 0, step: 0.1 },
      { key: 'tolerance', kind: 'number', label: 'Tolerance', required: false, default: 6, min: 0.001, step: 0.1 },
      { key: 'part', kind: 'select', label: 'Part', role: 'categorical', required: false },
      { key: 'operator', kind: 'select', label: 'Operator', role: 'categorical', required: false },
      { key: 'standard', kind: 'select', label: 'Attribute standard', role: 'any', required: false },
    ],
  },
  {
    id: 'qc.charts',
    module: 'qualityControl',
    moduleLabel: 'Quality Control',
    title: 'Control Charts',
    description: 'Subgroup, individuals, attributes, EWMA/CUSUM, rare-event g-chart.',
    phase: 7,
    implemented: true,
    frequentist: true,
    bayesian: false,
    fields: [
      { key: 'variable', kind: 'select', label: 'Series / count', role: 'numeric', required: true },
      { key: 'chartKind', kind: 'choice', label: 'Chart', required: true, options: [
        { value: 'individuals', label: 'Individuals (I-MR)' },
        { value: 'subgroup', label: 'X̄ (subgroup)' },
        { value: 'attributes', label: 'p chart' },
        { value: 'ewma', label: 'EWMA' },
        { value: 'cusum', label: 'CUSUM' },
        { value: 'rare', label: 'Rare-event g' },
      ] },
      { key: 'subgroup', kind: 'number', label: 'Subgroup size', required: false, default: 5, min: 2, step: 1 },
      { key: 'sampleSize', kind: 'number', label: 'p-chart n', required: false, default: 50, min: 1, step: 1 },
    ],
  },
  {
    id: 'qc.capability',
    module: 'qualityControl',
    moduleLabel: 'Quality Control',
    title: 'Process Capability',
    description: 'Cp, Cpk, Cpl, Cpu, Cpm vs specification limits.',
    phase: 7,
    implemented: true,
    frequentist: true,
    bayesian: false,
    fields: [
      { key: 'variable', kind: 'select', label: 'Process', role: 'numeric', required: true },
      { key: 'lsl', kind: 'number', label: 'LSL', required: true, default: 0, step: 0.1 },
      { key: 'usl', kind: 'number', label: 'USL', required: true, default: 10, step: 0.1 },
      { key: 'target', kind: 'number', label: 'Target', required: false, default: 5, step: 0.1 },
    ],
  },
  {
    id: 'qc.doe',
    module: 'qualityControl',
    moduleLabel: 'Quality Control',
    title: 'Design of Experiments',
    description: 'Factorial and response-surface analysis of an existing worksheet.',
    phase: 7,
    implemented: true,
    frequentist: true,
    bayesian: false,
    fields: [
      { key: 'response', kind: 'select', label: 'Response', role: 'numeric', required: true },
      { key: 'factors', kind: 'variables', label: 'Factors', role: 'numeric', multiple: true, required: true },
      { key: 'doeKind', kind: 'choice', label: 'Model', required: true, options: [
        { value: 'factorial', label: 'Factorial + 2-way' },
        { value: 'rsm', label: 'Response surface' },
      ] },
    ],
  },
  {
    id: 'robustT.modelAveraged',
    module: 'robustTTests',
    moduleLabel: 'Robust T-Tests',
    title: 'Robust T-Tests',
    description: 'Model-averaged t sampling models (Cauchy / t₄ / Gaussian) plus truncated JZS.',
    phase: 4,
    implemented: true,
    frequentist: false,
    bayesian: true,
    fields: [
      { key: 'variable', kind: 'select', label: 'Variable', role: 'numeric', required: true },
      { key: 'mu0', kind: 'number', label: 'Test value', required: true, default: 0, step: 0.1 },
      { key: 'rscale', kind: 'number', label: 'rscale', required: false, default: 0.707, min: 0.1, step: 0.01 },
    ],
  },
  {
    id: 'sem.sem',
    module: 'sem',
    moduleLabel: 'SEM',
    title: 'Structural Equation Modeling',
    description: 'CFA when indicators are assigned; otherwise a recursive observed-variable path model.',
    phase: 6,
    implemented: true,
    frequentist: true,
    bayesian: true,
    fields: [
      { key: 'variables', kind: 'variables', label: 'Indicators (CFA / latent SEM)', role: 'numeric', multiple: true, required: false },
      { key: 'nFactors', kind: 'number', label: 'Factors', required: false, default: 1, min: 1, max: 4, step: 1 },
      { key: 'endogenous', kind: 'select', label: 'Endogenous (path SEM)', role: 'numeric', required: false },
      { key: 'predictors', kind: 'variables', label: 'Predictors (path SEM)', role: 'numeric', multiple: true, required: false },
    ],
  },
  {
    id: 'sem.pls',
    module: 'sem',
    moduleLabel: 'SEM',
    title: 'Partial Least Squares SEM',
    description: 'Mode-A PLS with one exogenous and one endogenous composite.',
    phase: 6,
    implemented: true,
    frequentist: true,
    bayesian: false,
    fields: [
      { key: 'exogenousItems', kind: 'variables', label: 'Exogenous items', role: 'numeric', multiple: true, required: false },
      { key: 'endogenousItems', kind: 'variables', label: 'Endogenous items', role: 'numeric', multiple: true, required: false },
      { key: 'predictors', kind: 'variables', label: 'Exogenous (alias)', role: 'numeric', multiple: true, required: false },
      { key: 'endogenous', kind: 'select', label: 'Endogenous (single)', role: 'numeric', required: false },
    ],
  },
  {
    id: 'sem.mediation',
    module: 'sem',
    moduleLabel: 'SEM',
    title: 'Mediation Analysis',
    description: 'Observed mediation, MIMIC, MNLFA slope check, and latent growth.',
    phase: 6,
    implemented: true,
    frequentist: true,
    bayesian: true,
    fields: [
      { key: 'semKind', kind: 'choice', label: 'Model', required: true, options: [
        { value: 'mediation', label: 'Mediation (X, M, Y)' },
        { value: 'mimic', label: 'MIMIC' },
        { value: 'mnlfa', label: 'MNLFA (MIMIC slope)' },
        { value: 'growth', label: 'Latent growth' },
      ] },
      { key: 'x', kind: 'select', label: 'X', role: 'numeric', required: false },
      { key: 'm', kind: 'select', label: 'M', role: 'numeric', required: false },
      { key: 'y', kind: 'select', label: 'Y', role: 'numeric', required: false },
      { key: 'variables', kind: 'variables', label: 'Indicators (MIMIC / MNLFA)', role: 'numeric', multiple: true, required: false },
      { key: 'covariate', kind: 'select', label: 'Covariate', role: 'numeric', required: false },
      { key: 'measures', kind: 'variables', label: 'Occasions (growth)', role: 'numeric', multiple: true, required: false },
    ],
  },
  {
    id: 'survival.nonparametric',
    module: 'survival',
    moduleLabel: 'Survival',
    title: 'Non-parametric Survival',
    description: 'Kaplan–Meier, Greenwood SEs, log-rank, and Gehan–Breslow Wilcoxon.',
    phase: 5,
    implemented: true,
    frequentist: true,
    bayesian: false,
    fields: [
      { key: 'time', kind: 'select', label: 'Time', role: 'numeric', required: true },
      { key: 'event', kind: 'select', label: 'Event (1 = event)', role: 'any', required: true },
      { key: 'group', kind: 'select', label: 'Group (optional)', role: 'categorical', required: false },
    ],
  },
  {
    id: 'survival.cox',
    module: 'survival',
    moduleLabel: 'Survival',
    title: 'Semi-parametric Survival',
    description: 'Cox PH with Breslow ties and Schoenfeld residuals.',
    phase: 5,
    implemented: true,
    frequentist: true,
    bayesian: false,
    fields: [
      { key: 'time', kind: 'select', label: 'Time', role: 'numeric', required: true },
      { key: 'event', kind: 'select', label: 'Event (1 = event)', role: 'any', required: true },
      { key: 'covariates', kind: 'variables', label: 'Covariates', role: 'numeric', multiple: true, required: true },
    ],
  },
  {
    id: 'survival.parametric',
    module: 'survival',
    moduleLabel: 'Survival',
    title: 'Parametric Survival',
    description: 'Exponential, Weibull, log-normal, and log-logistic lifetime models.',
    phase: 5,
    implemented: true,
    frequentist: true,
    bayesian: false,
    fields: [
      { key: 'time', kind: 'select', label: 'Time', role: 'numeric', required: true },
      { key: 'event', kind: 'select', label: 'Event (1 = event)', role: 'any', required: true },
      { key: 'survFamily', kind: 'choice', label: 'Family', required: true, options: [
        { value: 'exponential', label: 'Exponential' },
        { value: 'weibull', label: 'Weibull' },
        { value: 'log-normal', label: 'Log-normal' },
        { value: 'log-logistic', label: 'Log-logistic' },
      ] },
    ],
  },
  {
    id: 'timeSeries.stationarity',
    module: 'timeSeries',
    moduleLabel: 'Time Series',
    title: 'Stationarity',
    description: 'ADF, KPSS, and Phillips–Perron tests.',
    phase: 5,
    implemented: true,
    frequentist: true,
    bayesian: false,
    fields: [
      { key: 'variable', kind: 'select', label: 'Series', role: 'numeric', required: true },
    ],
  },
  {
    id: 'timeSeries.arima',
    module: 'timeSeries',
    moduleLabel: 'Time Series',
    title: 'ARIMA',
    description: 'ACF/PACF identification, auto or manual p,d,q, CSS estimation, and forecasts.',
    phase: 5,
    implemented: true,
    frequentist: true,
    bayesian: false,
    fields: [
      { key: 'variable', kind: 'select', label: 'Series', role: 'numeric', required: true },
      { key: 'auto', kind: 'choice', label: 'Order', required: true, options: [{ value: 'auto', label: 'Auto (ADF + AIC)' }, { value: 'manual', label: 'Manual p,d,q' }] },
      { key: 'p', kind: 'number', label: 'p', required: false, default: 1, min: 0, max: 3, step: 1 },
      { key: 'd', kind: 'number', label: 'd', required: false, default: 0, min: 0, max: 2, step: 1 },
      { key: 'q', kind: 'number', label: 'q', required: false, default: 0, min: 0, max: 3, step: 1 },
      { key: 'horizon', kind: 'number', label: 'Forecast horizon', required: true, default: 8, min: 1, step: 1 },
    ],
  },
  {
    id: 'timeSeries.spectral',
    module: 'timeSeries',
    moduleLabel: 'Time Series',
    title: 'Spectral Analysis',
    description: 'Periodogram and Daniell-smoothed spectral density.',
    phase: 5,
    implemented: true,
    frequentist: true,
    bayesian: false,
    fields: [
      { key: 'variable', kind: 'select', label: 'Series', role: 'numeric', required: true },
    ],
  },
  {
    id: 'summaryStats.fromPublished',
    module: 'summaryStatistics',
    moduleLabel: 'Summary Statistics',
    title: 'Summary Statistics',
    description: 'Bayesian t, z, correlation, binomial, and A/B tests from published summaries.',
    phase: 4,
    implemented: true,
    frequentist: false,
    bayesian: true,
    allowEmptyData: true,
    fields: [
      { key: 'summaryKind', kind: 'choice', label: 'From', required: true, options: [
        { value: 't', label: 't' },
        { value: 'z', label: 'z' },
        { value: 'correlation', label: 'Correlation r' },
        { value: 'binomial', label: 'Binomial counts' },
        { value: 'ab', label: 'A/B two binomials' },
      ] },
      { key: 'stat', kind: 'number', label: 't / z / r', required: false, default: 2, step: 0.05 },
      { key: 'n', kind: 'number', label: 'n', required: false, default: 20, min: 3, step: 1 },
      { key: 'successes', kind: 'number', label: 'Successes', required: false, default: 12, min: 0, step: 1 },
      { key: 'p0', kind: 'number', label: 'p₀', required: false, default: 0.5, min: 0, max: 1, step: 0.01 },
      { key: 'k1', kind: 'number', label: 'Group 1 successes', required: false, default: 10, min: 0, step: 1 },
      { key: 'n1', kind: 'number', label: 'Group 1 n', required: false, default: 20, min: 1, step: 1 },
      { key: 'k2', kind: 'number', label: 'Group 2 successes', required: false, default: 12, min: 0, step: 1 },
      { key: 'n2', kind: 'number', label: 'Group 2 n', required: false, default: 20, min: 1, step: 1 },
      { key: 'rscale', kind: 'number', label: 'rscale', required: false, default: 0.707, min: 0.1, step: 0.01 },
    ],
  },
  ...visualModeling,
]

const PHASE4_BAYES_IDS = new Set([
  't.independent', 't.paired', 't.oneSample',
  'anova.between', 'anova.repeated', 'anova.ancova',
  'regression.correlation', 'regression.linear', 'regression.logistic',
  'frequencies.binomial', 'frequencies.multinomial', 'frequencies.contingency', 'frequencies.loglinear',
  'equivalence.t',
  'factor.cfa', 'sem.sem', 'sem.mediation',
  'meta.analysis', 'cochrane.ma', 'network.psych', 'bfpack.constrained',
  'acceptance.attribute', 'acceptance.variable', 'audit.sampling', 'audit.data', 'distributions.explorer',
])

export const ANALYSIS_CATALOG: AnalysisDef[] = RAW_CATALOG.map((item) => {
  if (!PHASE4_BAYES_IDS.has(item.id)) return item
  return {
    ...item,
    bayesian: true,
    description: `${item.description.replace(/\s*Bayesian [^.]* arrives in Phase 4\.?/g, '').trim()} Frequentist and Bayesian modes share this analysis.`,
  }
})

export const ANALYSIS_BY_ID = Object.fromEntries(ANALYSIS_CATALOG.map((item) => [item.id, item])) as Record<string, AnalysisDef>

export const JASP_MODULE_ORDER: JaspModuleId[] = [
  'descriptives', 'tTests', 'anova', 'mixedModels', 'regression', 'frequencies', 'factor',
  'acceptanceSampling', 'audit', 'bain', 'bayesFactorFunctions', 'bfpack', 'bsts', 'circular',
  'cochrane', 'distributions', 'equivalence', 'jags', 'learnBayes', 'learnStats', 'machineLearning',
  'metaAnalysis', 'network', 'power', 'predictiveAnalytics', 'process', 'prophet', 'qualityControl',
  'reliability', 'robustTTests', 'sem', 'survival', 'timeSeries', 'summaryStatistics', 'visualModeling',
]

export function analysesForModule(module: JaspModuleId) {
  return ANALYSIS_CATALOG.filter((item) => item.module === module)
}

export const LEGACY_PATH_TO_ANALYSIS: Record<string, string> = {
  '/explore/summary': 'descriptives.statistics',
  '/inference': 't.oneSample',
  '/explore/correlation': 'regression.correlation',
  '/explore/frequency': 'frequencies.contingency',
  '/regression': 'regression.linear',
}
